### ISSUE TITLE
ValueError: Could not find a format to read the specified file in single-image mode

### ISSUE THREAD

**Issue by Huimin-0000** [chsasank/Image-Rectification#2]
I just learned Python, there are a lot of things I don't understand, I don't know how to change it.
please help me. Thank you!

runfile('C:/Users/admin/Desktop/Image-Rectification-master/rectification.py', wdir='C:/Users/admin/Desktop/Image-Rectification-master')
Traceback (most recent call last):

  File "C:\Users\admin\Desktop\Image-Rectification-master\rectification.py", line 529, in <module>
    image = io.imread(image_name)

  File "C:\Users\admin\Anaconda3\envs\python\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)

  File "C:\Users\admin\Anaconda3\envs\python\lib\site-packages\skimage\io\manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)

  File "C:\Users\admin\Anaconda3\envs\python\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))

  File "C:\Users\admin\Anaconda3\envs\python\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)

  File "C:\Users\admin\Anaconda3\envs\python\lib\site-packages\imageio\core\functions.py", line 182, in get_reader
    "Could not find a format to read the specified file in %s mode" % modename

ValueError: Could not find a format to read the specified file in single-image mode

**Comment by boisbb** [comment]
Have you included a path to image you want to rectify as a first argument of the program?

**Comment by Huimin-0000** [comment]
Thank you for your answer,I already I already solve this problem.Your method is very good. It benefited me a lot.
 But I have many pictures to process them now. For a green hand, I don't know how to add a code to  batch processing.
Do you have any suggestions?
